version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mynDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Securpass4341
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  db_data:

